# ğŸ“ˆ Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # âš™ï¸ Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # ğŸ”„ Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# ğŸ”’ Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# â±ï¸ Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # ğŸ’¼ Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‚ Checkout
        uses: actions/checkout@v4
      - name: âš¡ï¸ Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: ğŸ“¦ Install dependencies
        run: npm ci
      - name: ğŸ› ï¸ Build
        run: npm run build
      - name: ğŸ“„ Setup Pages
        uses: actions/configure-pages@v4
      - name: ğŸ“‚ Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
